version: 2

sources:
  - name: raw
    database: PHYSIOPRO_DB      # optional if already defined
    schema: PHYSIOPRO_SCHEMA          # where Python writes to
    tables:
      - name: stg_rmse_results
